# Generated by Django 2.1.7 on 2019-03-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronzegaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_name',
            field=models.CharField(default='h', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='E:\\Bronzegaming\\media/games/'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='image',
            field=models.ImageField(upload_to='E:\\Bronzegaming\\media/games/'),
        ),
    ]
