# Generated by Django 2.1.7 on 2019-03-02 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bronzegaming', '0002_auto_20190301_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_going',
            field=models.ManyToManyField(blank=True, related_name='users_going', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='bronzegaming.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posting', to=settings.AUTH_USER_MODEL),
        ),
    ]
