# Generated by Django 2.1.7 on 2019-03-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronzegaming', '0005_event_user_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
