# Generated by Django 2.1.7 on 2019-03-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronzegaming', '0009_auto_20190302_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(to='bronzegaming.Game'),
        ),
        migrations.AddField(
            model_name='profile',
            name='platforms',
            field=models.ManyToManyField(to='bronzegaming.Platform'),
        ),
    ]
