# Generated by Django 2.1.7 on 2019-03-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronzegaming', '0010_auto_20190302_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(related_name='user', to='bronzegaming.Game'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platforms',
            field=models.ManyToManyField(related_name='user', to='bronzegaming.Platform'),
        ),
    ]
